version: "3.3"

services:
  app:
    build: .
    container_name: docker-node-project
    restart: always
    ports:
      - '80:51005'
   
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    env_file:
      - .env\mongo.env
  mysqldb:
    image: mysql:5.6
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file:
      - .env/mysql.env 
    volumes:
      - db:/data/db
    

volumes:
  db: